name: Jira Example

on:
  issues:
  push:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    if: github.event.action == 'opened'
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Jira Create issue
      uses: atlassian/gajira-create@v2.0.1
      with:
        # Key of the project
        project: AC
        # Type of the issue to be created. Example: 'Incident'
        issuetype: Task
        # Issue summary
        summary: ${{ github.event.issue.title}}
        # Issue description
        description: ${{ github.event.issue.body}}
